server:
 port: 8081
spring:
  application:
    name: AccountService
  datasource:
    url: jdbc:postgresql://postgres:5432/customerdb
    username: postgres
    password: XYZ1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect